$(document).ready(function() {
    var  menuLink = '<li><a href="https://grcodeclub.github.io">Αρχική Σελίδα</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = ' <li><a href="https://grcodeclub.github.io/system">Λειτουργικό Σύστημα</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = ' <li><a href="https://grcodeclub.github.io/system/post/ορολογία">Ορολογία</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/windows">Microsoft Windows</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/linux">Linux</li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/android">Android</li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/system/post/list">Έγγραφα</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/system/post/extensions_files">Επεκτάσεις Αρχείων</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li><a href="https://grcodeclub.github.io/system/post/file-system">Σύστημα αρχείων</a></li>';
    $('.sidebarMenuInner').append(menuLink);
    menuLink = '<li style="height: 200px;"></li>';
    $('.sidebarMenuInner').append(menuLink);
  });
